name: Deploy to Raspberry Pi 5 (Docker)

on:
  push:
    branches: [ "readyToCiCd" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env file
      run: |
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
        echo "CONFIG_URL=${{ secrets.CONFIG_URL }}" >> .env

    - name: Run Docker Compose
      run: |
        docker compose down
        docker compose up --build -d
